# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-13 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('post_id', models.TextField(null=True)),
                ('commenter_id', models.TextField(null=True)),
                ('message', models.TextField(null=True)),
                ('media_url', models.TextField(null=True)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.TextField(null=True)),
                ('post_id', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('target_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('message', models.TextField(null=True)),
                ('story', models.TextField(null=True)),
                ('privacy', models.IntegerField(null=True)),
                ('status_type', models.IntegerField(null=True)),
                ('object_id', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('other_urls', models.TextField(null=True)),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.TextField(null=True)),
                ('post_id', models.TextField(null=True)),
                ('video_url', models.TextField(null=True)),
                ('target_url', models.TextField(null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together=set([('post_id', 'video_url')]),
        ),
        migrations.AlterUniqueTogether(
            name='photos',
            unique_together=set([('post_id', 'image_url')]),
        ),
    ]
