# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-14 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='local_image_url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='videos',
            name='local_video_url',
            field=models.TextField(null=True),
        ),
    ]
